image: docker:19.03.8

variables:
  IMAGE_NAME: $REGISTRY/th2-recon-template
  VERSION: "2.0"
  MAINTENANCE: "3"

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

build_master:
  tags:
  - docker-in-docker
  stage: build
  script:
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest  --tag $IMAGE_NAME:$VERSION.$MAINTENANCE --tag $IMAGE_NAME:latest --build-arg USERNAME=$NEXUS_USERNAME --build-arg PASSWORD=$NEXUS_PASSWORD .
    - docker push $IMAGE_NAME:$VERSION.$MAINTENANCE
    - docker push $IMAGE_NAME:latest
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"

build_branch:
  variables:
    IMAGE_NAME: $REGISTRY/th2-recon-template/$CI_COMMIT_REF_SLUG
  tags:
  - docker-in-docker
  stage: build
  script:
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest  --tag $IMAGE_NAME:$VERSION.$MAINTENANCE --tag $IMAGE_NAME:latest --build-arg USERNAME=$NEXUS_USERNAME --build-arg PASSWORD=$NEXUS_PASSWORD .
    - docker push $IMAGE_NAME:$VERSION.$MAINTENANCE
    - docker push $IMAGE_NAME:latest
  only:
    variables:
      - $CI_COMMIT_REF_NAME != "master"