variables:
  APP_NAME: 'th2-check2-recon-template'
  MAJOR_VERSION: '2'
  MINOR_VERSION: '0'
  MAINTENANCE_VERSION: '4-6'
  PYPI_PUBLISH_ENABLED: "false"

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-python.yml'
